server:
  port: 9004
eureka:
  client:
    registerWithEureka: false #不在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka
feign:
  hystrix:
    enabled: true #开启熔断支持
  client:
    config:
     remote-service:           #服务名，填写default为所有服务
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


